matrix:
  include:
    - langauge: objective-c
      osx_image: xcode9.3
      script:
        - cd /Source/iOS/Harvest
        - set -o pipefail
        - xcodebuild -workspace Harvest.xcworkspace -scheme Harvest -destination "platform=iOS Simulator,name=iPhone 6S" test