matrix:
  include:
    - langauge: objective-c
      osx_image: xcode9.3
      os: osx
      xcode_workspace: Source/iOS/Harvest/Harvest.xcworkspace
      xcode_scheme: Harvest
      
      env:
        - WORKSPACE: "Source/iOS/Harvest/Harvest.xcworkspace"
        
      script:
        - set -o pipefail
        - rm Podfile.lock
        - pod install
        - xcodebuild -workspace "$WORKSPACE" -scheme Harvest -destination "platform=iOS Simulator,name=iPhone 6S" test